# Generated by Django 2.1.5 on 2020-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('inUse', models.BooleanField(default=False)),
            ],
        ),
    ]
