# Generated by Django 2.1.5 on 2020-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='secret',
            field=models.IntegerField(null=True),
        ),
    ]
