# Generated by Django 2.1.5 on 2020-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_link_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='secret',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
